package com.iut.banque.test.selenium;



import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.WebElement;
import org.junit.Assert;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.WebDriverWait;


import static org.junit.Assert.assertNotNull;


public class SeleniumTests {
    private WebDriver driver;
    private Map<String, Object> vars;
    private JavascriptExecutor js;
    private WebDriverWait wait;

    @Before
    public void setUp() {
        // Initialisation du driver WebDriver et configuration pour Firefox en mode headless
        System.setProperty("webdriver.gecko.driver", "/app/drivers/geckodriver");
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");

        driver = new FirefoxDriver(options); // Utilisation de la variable globale 'driver'
        assertNotNull("Le driver n'a pas été initialisé correctement", driver); // Vérification de l'initialisation du driver
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        wait = new WebDriverWait(driver, 10); // Attente de 10 secondes pour que tous les éléments se chargent correctement
    }

    @After
    public void tearDown() {
        // Fermeture du navigateur après les tests
        if (driver != null) {
            driver.quit();
        }
    }

    @Test
    public void testAffichageLogoUnivDansLAccueil() {
        driver.get("http://tomcat-server:8080/AS_Bank");
        WebElement logo = driver.findElement(By.xpath("/html/body/p[1]/img")); // logo univ-lorraine (utilisation du XPath)

        Assert.assertTrue("Le logo ne s'affiche pas", logo.isDisplayed());
        tearDown();
    }

    @Test
    public void testConnexionUtilisateur() {
        driver.get("http://tomcat-server:8080/AS_Bank");
        driver.findElement(By.xpath("/html/body/p[2]/a")).click();
        WebElement usernameField = driver.findElement(By.id("controller_Connect_login_action_userCde"));
        WebElement passwordField = driver.findElement(By.id("controller_Connect_login_action_userPwd"));

        usernameField.sendKeys("client1");
        passwordField.sendKeys("clientpass1");

        WebElement submitButton = driver.findElement(By.id("controller_Connect_login_action_submit"));
        submitButton.click();

        WebElement msggBienV = driver.findElement(By.xpath("/html/body/p[1]/b")); // nom + type compte de l'utilisateur connecté (utilisation du XPath)

        Assert.assertNotNull(msggBienV);

        tearDown();

    }
}
