name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.1  
        env:
          MYSQL_ROOT_PASSWORD: root123  
          MYSQL_DATABASE: default_db      
          MYSQL_USER: user
          MYSQL_PASSWORD: user123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'  # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Attendre que MariaDB soit prêt et que le conteneur démarre complètement
      - name: Wait for MariaDB to be ready
        run: |
          until docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysqladmin --user=root --password=root123 --host=127.0.0.1 --port=3306 ping --silent; do
            echo "Waiting for MariaDB to be ready..."
            sleep 5
          done
          sleep 25


       # Créer la base de données projet_devops
      - name: Create projet_devops database
        run: |
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -proot123 -e "CREATE DATABASE IF NOT EXISTS projet_devops;"
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") mysql -u root -proot123 -e "CREATE DATABASE IF NOT EXISTS projet_devops_test;"

      # Copier et vérifier la présence de projet_devops.sql
      - name: Copy and verify projet_devops.sql
        run: |
          docker cp "$GITHUB_WORKSPACE/db_files_with_argon2hash_passwd/projet_devops.sql" $(docker ps -q --filter "ancestor=mariadb:10.4.1"):/tmp/projet_devops.sql
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") ls /tmp/projet_devops.sql || echo "File not found in container!"

      # Importer projet_devops.sql en utilisant cat pour éviter les problèmes de redirection
      - name: Import projet_devops.sql
        run: |
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") /bin/sh -c "cat /tmp/projet_devops.sql | mysql -u root -proot123 projet_devops"

      - name: Copy and import projet_devops_test.sql
        run: |
          docker cp "$GITHUB_WORKSPACE/db_files_with_argon2hash_passwd/projet_devops_test.sql" $(docker ps -q --filter "ancestor=mariadb:10.4.1"):/tmp/projet_devops_test.sql
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") ls /tmp/projet_devops_test.sql || echo "File not found in container!"
          docker exec $(docker ps -q --filter "ancestor=mariadb:10.4.1") /bin/sh -c "cat /tmp/projet_devops_test.sql | mysql -u root -proot123 projet_devops_test"


      - name: Build and analyze
        working-directory: ./_00_ASBank2023
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=llUnknowUsernamell_projet-DevOps-grp1
